version: "3.9"
services:
  client:
    build:
      context: "../tic-tac-toe-client"
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: "../tic-tac-toe-client/src"
        target: "/app/src"
    depends_on:
      - state
  state:
    build:
      context: "../tic-tac-toe-state"
    ports:
      - "3001:3000"
    volumes:
      - type: bind
        source: "../tic-tac-toe-state/src"
        target: "/app/src"
