version: "3.9"
services:
  client:
    build:
      context: "../tic-tac-toe-client"
    ports:
      - "3000:3000"
    links:
      - state
  state:
    build:
      context: "../tic-tac-toe-web"
    ports:
      - "3001:3000"
